import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { Toaster } from "sonner";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import AuthGuard from "./components/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inmo - Updated Always",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <AuthGuard>
            <Toaster richColors />
            <Providers>{children}</Providers>
          </AuthGuard>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
